rootProject.name = 'sklearn-java'

include 'core'
include 'math'
include 'datasets'
include 'preprocessing'
include 'linear_model'
include 'neighbors'
include 'tree'
include 'ensemble'
include 'cluster'
include 'svm'
include 'naive_bayes'
include 'metrics'
include 'model_selection'
include 'pipeline'
include 'feature_selection'
include 'decomposition'
include 'neural_network'
include 'impute'
include 'dummy'
include 'utils'
